# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FlightLog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FlightLog.proto',
  package='buffers',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x46lightLog.proto\x12\x07\x62uffers\"\xa4\x06\n\x07sensors\x12!\n\x03gps\x18\x01 \x01(\x0b\x32\x14.buffers.sensors.GPS\x12)\n\x07\x63ompass\x18\x02 \x01(\x0b\x32\x18.buffers.sensors.Compass\x12(\n\x04\x62\x61ro\x18\x03 \x01(\x0b\x32\x1a.buffers.sensors.Barometre\x12+\n\x08waypoint\x18\x04 \x01(\x0b\x32\x19.buffers.sensors.Waypoint\x12)\n\x06target\x18\x05 \x01(\x0b\x32\x19.buffers.sensors.Location\x12\'\n\x04home\x18\x06 \x01(\x0b\x32\x19.buffers.sensors.Location\x12\x10\n\x08init_alt\x18\x07 \x01(\x02\x12\x18\n\x10\x44istanceToTarget\x18\x08 \x01(\x02\x12\x18\n\x10\x44istanceFromHome\x18\t \x01(\x02\x1a\x41\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x1a\x34\n\x08\x41ttitude\x12\r\n\x05pitch\x18\x01 \x01(\x02\x12\x0c\n\x04roll\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x1a-\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1aT\n\x03GPS\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x11\n\tnum_stars\x18\x02 \x01(\x05\x12+\n\x08location\x18\x03 \x01(\x0b\x32\x19.buffers.sensors.Location\x1a\x45\n\x07\x43ompass\x12\r\n\x05state\x18\x01 \x01(\x08\x12+\n\x08\x61ttitude\x18\x02 \x01(\x0b\x32\x19.buffers.sensors.Attitude\x1aS\n\tBarometre\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x10\n\x08Pressure\x18\x02 \x01(\x02\x12\x13\n\x0bTemperature\x18\x03 \x01(\x02\x12\x10\n\x08\x41ltitude\x18\x04 \x01(\x02\x1a@\n\x08Waypoint\x12\n\n\x02ID\x18\x01 \x01(\x05\x12(\n\x05point\x18\x02 \x03(\x0b\x32\x19.buffers.sensors.Locationb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORS_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='buffers.sensors.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='buffers.sensors.Location.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='buffers.sensors.Location.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='buffers.sensors.Location.altitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=424,
)

_SENSORS_ATTITUDE = _descriptor.Descriptor(
  name='Attitude',
  full_name='buffers.sensors.Attitude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='buffers.sensors.Attitude.pitch', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='buffers.sensors.Attitude.roll', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='buffers.sensors.Attitude.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=478,
)

_SENSORS_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='buffers.sensors.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='buffers.sensors.Coordinate.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='buffers.sensors.Coordinate.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='buffers.sensors.Coordinate.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=525,
)

_SENSORS_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='buffers.sensors.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='buffers.sensors.GPS.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_stars', full_name='buffers.sensors.GPS.num_stars', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='buffers.sensors.GPS.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=611,
)

_SENSORS_COMPASS = _descriptor.Descriptor(
  name='Compass',
  full_name='buffers.sensors.Compass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='buffers.sensors.Compass.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude', full_name='buffers.sensors.Compass.attitude', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=682,
)

_SENSORS_BAROMETRE = _descriptor.Descriptor(
  name='Barometre',
  full_name='buffers.sensors.Barometre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='buffers.sensors.Barometre.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Pressure', full_name='buffers.sensors.Barometre.Pressure', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temperature', full_name='buffers.sensors.Barometre.Temperature', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='buffers.sensors.Barometre.Altitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=767,
)

_SENSORS_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='buffers.sensors.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='buffers.sensors.Waypoint.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='buffers.sensors.Waypoint.point', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=833,
)

_SENSORS = _descriptor.Descriptor(
  name='sensors',
  full_name='buffers.sensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps', full_name='buffers.sensors.gps', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compass', full_name='buffers.sensors.compass', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baro', full_name='buffers.sensors.baro', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='buffers.sensors.waypoint', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='buffers.sensors.target', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='home', full_name='buffers.sensors.home', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_alt', full_name='buffers.sensors.init_alt', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DistanceToTarget', full_name='buffers.sensors.DistanceToTarget', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DistanceFromHome', full_name='buffers.sensors.DistanceFromHome', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SENSORS_LOCATION, _SENSORS_ATTITUDE, _SENSORS_COORDINATE, _SENSORS_GPS, _SENSORS_COMPASS, _SENSORS_BAROMETRE, _SENSORS_WAYPOINT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=833,
)

_SENSORS_LOCATION.containing_type = _SENSORS
_SENSORS_ATTITUDE.containing_type = _SENSORS
_SENSORS_COORDINATE.containing_type = _SENSORS
_SENSORS_GPS.fields_by_name['location'].message_type = _SENSORS_LOCATION
_SENSORS_GPS.containing_type = _SENSORS
_SENSORS_COMPASS.fields_by_name['attitude'].message_type = _SENSORS_ATTITUDE
_SENSORS_COMPASS.containing_type = _SENSORS
_SENSORS_BAROMETRE.containing_type = _SENSORS
_SENSORS_WAYPOINT.fields_by_name['point'].message_type = _SENSORS_LOCATION
_SENSORS_WAYPOINT.containing_type = _SENSORS
_SENSORS.fields_by_name['gps'].message_type = _SENSORS_GPS
_SENSORS.fields_by_name['compass'].message_type = _SENSORS_COMPASS
_SENSORS.fields_by_name['baro'].message_type = _SENSORS_BAROMETRE
_SENSORS.fields_by_name['waypoint'].message_type = _SENSORS_WAYPOINT
_SENSORS.fields_by_name['target'].message_type = _SENSORS_LOCATION
_SENSORS.fields_by_name['home'].message_type = _SENSORS_LOCATION
DESCRIPTOR.message_types_by_name['sensors'] = _SENSORS

sensors = _reflection.GeneratedProtocolMessageType('sensors', (_message.Message,), dict(

  Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_LOCATION,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Location)
    ))
  ,

  Attitude = _reflection.GeneratedProtocolMessageType('Attitude', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_ATTITUDE,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Attitude)
    ))
  ,

  Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_COORDINATE,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Coordinate)
    ))
  ,

  GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_GPS,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.GPS)
    ))
  ,

  Compass = _reflection.GeneratedProtocolMessageType('Compass', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_COMPASS,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Compass)
    ))
  ,

  Barometre = _reflection.GeneratedProtocolMessageType('Barometre', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_BAROMETRE,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Barometre)
    ))
  ,

  Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
    DESCRIPTOR = _SENSORS_WAYPOINT,
    __module__ = 'FlightLog_pb2'
    # @@protoc_insertion_point(class_scope:buffers.sensors.Waypoint)
    ))
  ,
  DESCRIPTOR = _SENSORS,
  __module__ = 'FlightLog_pb2'
  # @@protoc_insertion_point(class_scope:buffers.sensors)
  ))
_sym_db.RegisterMessage(sensors)
_sym_db.RegisterMessage(sensors.Location)
_sym_db.RegisterMessage(sensors.Attitude)
_sym_db.RegisterMessage(sensors.Coordinate)
_sym_db.RegisterMessage(sensors.GPS)
_sym_db.RegisterMessage(sensors.Compass)
_sym_db.RegisterMessage(sensors.Barometre)
_sym_db.RegisterMessage(sensors.Waypoint)


# @@protoc_insertion_point(module_scope)
