SystemID = 4
version = "beta"
# version = "alpha"
client_id = "FC"
debug = false
open_module = [
    # 'Sbus',
    # 'Compass',
    # 'GPS',
    # 'Baro',
    # 'IMU',
    # 'Lidar',
    'GCS'
]

commands = [
    'arm()',
    # 'set_channels_mid()',
    # 'set_gear(2)',
    # 'yaw_left_brake()',
    # 'yaw_right_brake()',
    # 'roll_left_brake()',
    # 'roll_right_brake()',
    # 'forward_brake()',
    # 'backward_brake()',
    # 'up_brake()'
    # 'down_brake()',
    'condition_yaw(30)',
    # 'condition_yaw(300)',
    # 'Guided()',
    # 'download()',
    # 'Auto()',
    'disarm()',
]

[System4]
    UAV="HELI800" 
    Model='HELI' 
    MainController='ACE_ONE'
    AIL = [1,352,1024,1696,1,20]
    ELE = [2,352,1024,1696,-1,20]
    THR = [3,252,998,1655,1,15]
    RUD = [4,352,1020,1696,-1,12]
    Mode = [7,487,1561,1561]
    Rate = [5,,1328,1328,1328]
    PIT = [6,352,697,1158,-1]
    Switch = [8,487,1024,1561]
    Gear = [20,40,60]
    [System4.direction]
    P=0.5
    I=0
    D=0
    error=5
    maxoutput=15
    min = 5
    overshoot=1.3
    success_time=30

[System2]
    UAV="HEX8" 
    Model='HEX' 
    MainController='N3'
    AIL = [1,352,1024,1696,1,20]
    ELE = [2,352,1046,1696,-1,20]
    THR = [3,352,1040,1696,-1,15]
    RUD = [4,352,1028,1696,1,15]
    Mode = [6,352,352,1696]
    Aux1 = [5,,352,1024,1696]
    Aux2 = [7,1024,1024,1024]
    Switch = [8,352,1024,1696]
    Gear = [20,40,60]
    [System2.direction]
    P=60
    I=5
    D=0
    error=5
    maxoutput=30
    min = 10
    overshoot=1.3
    success_time=30

[System1]
    UAV="HEX6" 
    Model='HEX' 
    MainController='NAZA-v2'
    AIL = [1,352,1024,1696,1,20]
    ELE = [2,352,1046,1696,-1,20]
    THR = [3,352,1020,1696,-1,15]
    RUD = [4,352,1028,1696,1,15]
    Mode = [5,494,1561,1561]
    Aux1 = [6,,1024,1024,1024]
    Aux2 = [7,494,1024,1554]
    Switch = [8,352,1024,1696]
    Gear = [20,40,60]
    [System1.direction]
    P=0.5
    I=0
    D=0
    error=5
    maxoutput=15
    min = 5
    overshoot=1.3
    success_time=30
    

[System3]
    UAV="HELI550" 
    Model='HELI' 
    MainController='ACE_ONE'
    AIL = [1,352,1024,1696,-1,20]
    ELE = [2,352,1046,1696,-1,20]
    THR = [3,279,1143,1716,1,15]
    RUD = [4,352,1020,1696,-1,12]
    Mode = [7,487,1561,1561]
    Rate = [5,,1312,1312,1312]
    PIT = [6,352,746,1171,-1]
    Switch = [8,352,1024,1696]
    Gear = [20,40,60]
    [System3.direction]
    P=0.5
    I=0
    D=0
    error=5
    maxoutput=15
    min = 5
    overshoot=1.3
    success_time=30


[MQTT]
    [MQTT.keyboard]
    host = '192.168.1.4'
    port = 1883
    [MQTT.lidar]
    host = 'localhost'
    port = 1883


[RPC]  
    [RPC.OA]
    host = 'localhost'
    port = '12345'

[sbus]
    port = '/dev/sbus'
    baudrate = 100000

[GPS]
    port = '/dev/GPS'
    baudrate = 9600

[compass]
    port = '/dev/compass'
    baudrate = 9600
    type = '2D'

[IMU]
    port = '/dev/IMU'
    baudrate = 115200

[topic]
    keyboard = 'keyboard'
    [topic.publish]
    full = 'Context'
    semi = 'Control'
    [topic.subscribe]
    full = 'Full-Automatic'
    semi = 'Semi-Automatic'

    
