# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oa_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oa_rpc.proto',
  package='oa_rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0coa_rpc.proto\x12\x06oa_rpc\"\xac\x01\n\x0b\x46ullContext\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06target\x18\x02 \x01(\x05\x12\x0f\n\x07\x65psilon\x18\x03 \x01(\r\x12\x1f\n\x07\x63urrent\x18\x04 \x03(\x0e\x32\x0e.oa_rpc.Action\x12\"\n\nlast_state\x18\x05 \x03(\x0e\x32\x0e.oa_rpc.Action\x12+\n\x13last_previous_state\x18\x06 \x03(\x0e\x32\x0e.oa_rpc.Action\":\n\x0bSemiContext\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1f\n\x07\x61\x63tions\x18\x02 \x03(\x0e\x32\x0e.oa_rpc.Action\"7\n\x08Strategy\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1f\n\x07\x61\x63tions\x18\x02 \x03(\x0e\x32\x0e.oa_rpc.Action*\x94\x01\n\x06\x41\x63tion\x12\x08\n\x04STOP\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x02\x12\x0c\n\x08LEFT_YAW\x10\x04\x12\r\n\tRIGHT_YAW\x10\x08\x12\r\n\tLEFT_ROLL\x10\x10\x12\x0e\n\nRIGHT_ROLL\x10 \x12\x06\n\x02UP\x10@\x12\t\n\x04\x44OWN\x10\x80\x01\x12\x0c\n\x07INVALID\x10\xee\x01\x12\x08\n\x03\x41NY\x10\xff\x01\x32\x87\x01\n\x11ObstacleAvoidance\x12\x38\n\rFullAutomatic\x12\x13.oa_rpc.FullContext\x1a\x10.oa_rpc.Strategy\"\x00\x12\x38\n\rSemiAutomatic\x12\x13.oa_rpc.SemiContext\x1a\x10.oa_rpc.Strategy\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='oa_rpc.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKWARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_YAW', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_YAW', index=4, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_ROLL', index=5, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_ROLL', index=6, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=7, number=64,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=8, number=128,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=9, number=238,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANY', index=10, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=465,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
STOP = 0
FORWARD = 1
BACKWARD = 2
LEFT_YAW = 4
RIGHT_YAW = 8
LEFT_ROLL = 16
RIGHT_ROLL = 32
UP = 64
DOWN = 128
INVALID = 238
ANY = 255



_FULLCONTEXT = _descriptor.Descriptor(
  name='FullContext',
  full_name='oa_rpc.FullContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oa_rpc.FullContext.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='oa_rpc.FullContext.target', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='oa_rpc.FullContext.epsilon', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current', full_name='oa_rpc.FullContext.current', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_state', full_name='oa_rpc.FullContext.last_state', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_previous_state', full_name='oa_rpc.FullContext.last_previous_state', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=197,
)


_SEMICONTEXT = _descriptor.Descriptor(
  name='SemiContext',
  full_name='oa_rpc.SemiContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oa_rpc.SemiContext.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='oa_rpc.SemiContext.actions', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=257,
)


_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='oa_rpc.Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oa_rpc.Strategy.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='oa_rpc.Strategy.actions', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=314,
)

_FULLCONTEXT.fields_by_name['current'].enum_type = _ACTION
_FULLCONTEXT.fields_by_name['last_state'].enum_type = _ACTION
_FULLCONTEXT.fields_by_name['last_previous_state'].enum_type = _ACTION
_SEMICONTEXT.fields_by_name['actions'].enum_type = _ACTION
_STRATEGY.fields_by_name['actions'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['FullContext'] = _FULLCONTEXT
DESCRIPTOR.message_types_by_name['SemiContext'] = _SEMICONTEXT
DESCRIPTOR.message_types_by_name['Strategy'] = _STRATEGY
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION

FullContext = _reflection.GeneratedProtocolMessageType('FullContext', (_message.Message,), dict(
  DESCRIPTOR = _FULLCONTEXT,
  __module__ = 'oa_rpc_pb2'
  # @@protoc_insertion_point(class_scope:oa_rpc.FullContext)
  ))
_sym_db.RegisterMessage(FullContext)

SemiContext = _reflection.GeneratedProtocolMessageType('SemiContext', (_message.Message,), dict(
  DESCRIPTOR = _SEMICONTEXT,
  __module__ = 'oa_rpc_pb2'
  # @@protoc_insertion_point(class_scope:oa_rpc.SemiContext)
  ))
_sym_db.RegisterMessage(SemiContext)

Strategy = _reflection.GeneratedProtocolMessageType('Strategy', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGY,
  __module__ = 'oa_rpc_pb2'
  # @@protoc_insertion_point(class_scope:oa_rpc.Strategy)
  ))
_sym_db.RegisterMessage(Strategy)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class ObstacleAvoidanceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.FullAutomatic = channel.unary_unary(
          '/oa_rpc.ObstacleAvoidance/FullAutomatic',
          request_serializer=FullContext.SerializeToString,
          response_deserializer=Strategy.FromString,
          )
      self.SemiAutomatic = channel.unary_unary(
          '/oa_rpc.ObstacleAvoidance/SemiAutomatic',
          request_serializer=SemiContext.SerializeToString,
          response_deserializer=Strategy.FromString,
          )


  class ObstacleAvoidanceServicer(object):

    def FullAutomatic(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SemiAutomatic(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ObstacleAvoidanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'FullAutomatic': grpc.unary_unary_rpc_method_handler(
            servicer.FullAutomatic,
            request_deserializer=FullContext.FromString,
            response_serializer=Strategy.SerializeToString,
        ),
        'SemiAutomatic': grpc.unary_unary_rpc_method_handler(
            servicer.SemiAutomatic,
            request_deserializer=SemiContext.FromString,
            response_serializer=Strategy.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'oa_rpc.ObstacleAvoidance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaObstacleAvoidanceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FullAutomatic(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SemiAutomatic(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaObstacleAvoidanceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FullAutomatic(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    FullAutomatic.future = None
    def SemiAutomatic(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    SemiAutomatic.future = None


  def beta_create_ObstacleAvoidance_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('oa_rpc.ObstacleAvoidance', 'FullAutomatic'): FullContext.FromString,
      ('oa_rpc.ObstacleAvoidance', 'SemiAutomatic'): SemiContext.FromString,
    }
    response_serializers = {
      ('oa_rpc.ObstacleAvoidance', 'FullAutomatic'): Strategy.SerializeToString,
      ('oa_rpc.ObstacleAvoidance', 'SemiAutomatic'): Strategy.SerializeToString,
    }
    method_implementations = {
      ('oa_rpc.ObstacleAvoidance', 'FullAutomatic'): face_utilities.unary_unary_inline(servicer.FullAutomatic),
      ('oa_rpc.ObstacleAvoidance', 'SemiAutomatic'): face_utilities.unary_unary_inline(servicer.SemiAutomatic),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ObstacleAvoidance_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('oa_rpc.ObstacleAvoidance', 'FullAutomatic'): FullContext.SerializeToString,
      ('oa_rpc.ObstacleAvoidance', 'SemiAutomatic'): SemiContext.SerializeToString,
    }
    response_deserializers = {
      ('oa_rpc.ObstacleAvoidance', 'FullAutomatic'): Strategy.FromString,
      ('oa_rpc.ObstacleAvoidance', 'SemiAutomatic'): Strategy.FromString,
    }
    cardinalities = {
      'FullAutomatic': cardinality.Cardinality.UNARY_UNARY,
      'SemiAutomatic': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'oa_rpc.ObstacleAvoidance', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
